urls.py
from django.conf.urls.defaults import patterns, include, url
#from django.views.generic.simple import direct_to_template
from main import views
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shortlist.views.home', name='home'),
    # url(r'^shortlist/', include('shortlist.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration_email.backends.default.urls')),
    #url(r'^$', direct_to_template,
    # { 'template': 'base.html' }, 'home_page'),
    url(r'^$', views.homepage, name='index'),
    url(r'^admin_panel/$', views.admin_panel, name='admin-panel'),
    url(r'^job/(?P<job_id>\w+)/$', views.job_status, name='job_status'),
    url(r'^applicants/(?P<job_id>\w+)/$',views.refresh_applicants, name='refresh_applicants'),
    url(r'^best_match/(?P<job_id>\w+)/$',views.best_match, name='best_match'),
    url(r'^skill_filter/(?P<job_id>\w+)/$',views.skill_filter, name='skill_filter'),
    url(r'^experience_filter/(?P<job_id>\w+)/$',views.xperience_filter, name='xperience_filter'),
    url(r'^academic_filter/(?P<job_id>\w+)/$',views.academic_filter, name='academic_filter'),
    url(r'^post_job/$',views.post_job, name='post_job'),
    url(r'^apply/(?P<job_id>\w+)/$',views.apply, name='apply'),
    url(r'^(?P<job_id>\w+)/(?P<candidate_id>\w+)/filter/$',views.filter, name='filter'),
    url(r'^(?P<job_id>\w+)/(?P<candidate_id>\w+)/shortlist/$',views.shortlist, name='shortlist'),
    url(r'^(?P<job_id>\w+)/shortlisted/$',views.view_shortlisted, name='view_shortlisted'),
    #url(r'^(?P<shortlist_id>\w+)/$',views.remove_shortlisted, name='remove'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}))

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

main/models.py
import os
from django.db import models
from djangotoolbox.fields import EmbeddedModelField, ListField
import hashlib
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
# Create your models here.

def get_file_path(instance, filename):
    return os.path.join('files', hashlib.md5(str(datetime.datetime.now)).hexdigest())


class Job(models.Model):
    owner = models.ForeignKey(User, unique=False)
    age_limit = models.IntegerField()
    name = models.CharField(max_length=200)
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    is_filtered = models.BooleanField(default=False)
    skillset = models.TextField(max_length=255)
    years_of_experience = models.IntegerField()
    academics = models.CharField(max_length=255)
    posted_on = models.DateTimeField(auto_now_add=True)
    job_url = models.CharField(max_length=255, blank=True)
    last_application_date = models.DateField(blank=True)
    applicant_limit = models.IntegerField()
    applicants = models.IntegerField(default=0)

    class Meta:
        db_table = 'Job'
        ordering = ['-posted_on']
        verbose_name_plural = 'Jobs'

    def save(self, force_insert=False, force_update=False):
        self.applicants+=1
        super(Job, self).save(force_insert, force_update)

    def __unicode__(self):
        return u'%s' % self.id
    @models.permalink
    def get_absolute_url(self):
        return ('jobs_job', (), { 'job_id': self.id })

import os
def notify(sender, instance, **kwargs):
    if instance.job_url == '':
        post_save.disconnect(notify, sender=Job)
        url = "http://" + settings.SITE + "/apply/" + instance.id + "/"
        instance.job_url = url
        instance.save()

post_save.connect(notify, sender=Job, dispatch_uid="main.models")

class Candidate(models.Model):
    job = models.ForeignKey('Job', unique=False)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    cv = models.FileField(upload_to=get_file_path)
    years_of_experience = models.IntegerField()
    skillset = models.CharField(max_length=255)
    academics = models.CharField(max_length=255)
    applied_on = models.DateTimeField(auto_now_add=True)
    filtered_out = models.BooleanField(default=False)
    shortlisted = models.BooleanField(default=False)
    number = models.CharField(max_length=50)
    cover_letter = models.TextField(blank=True)
    class Meta:
        db_table = 'Candidate'
        ordering = ['-applied_on']
        verbose_name_plural = 'Candidates'
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('jobs_candidate', (), { 'candidate_name': self.email })

class Shortlist(models.Model):
    job = models.ForeignKey('Job', unique=False)
    email = models.EmailField()
    can_id = models.CharField(max_length=250)
    name = models.CharField(max_length=200)
    shortlisted_on = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = 'Shortlist'
        ordering = ['-shortlisted_on']
        verbose_name_plural = 'Shortlists'
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('jobs_shortlist', (), { 'shortlist_name': self.email })

main/views.py
# Create your views here.
from django.template import RequestContext
from django.shortcuts import render_to_response
from main.models import Job, Candidate, Shortlist
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
import nltk
from nltk.corpus import stopwords
from django.utils import simplejson
import jellyfish
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from forms import JobForm, ApplicationForm
import os
from django.conf import settings


def get_user(email):
    try:
        return User.objects.get(email=email.lower())
    except User.DoesNotExist:
        return None

def homepage(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        username = get_user(email)
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect("/admin_panel/")
            else:
                # Return a 'disabled account' error message
                pass
        else:
            return render_to_response("home.html", context_instance=RequestContext(request))
    else:
        return render_to_response("home.html", context_instance=RequestContext(request))

@login_required
def admin_panel(request):
    my_jobs = Job.objects.filter(owner=request.user.id)
    return render_to_response("main/admin-panel.html", locals(), context_instance=RequestContext(request))

@login_required
def job_status(request, job_id):
    details = Job.objects.get(id=job_id)
    candidates = Candidate.objects.filter(job=job_id, filtered_out=False)
    shortlists = Shortlist.objects.filter(job=job_id)
    return render_to_response("main/details.html", locals(), context_instance=RequestContext(request))

@login_required
def refresh_applicants(request, job_id):
    applicants = list(Candidate.objects.filter(job=job_id, filtered_out=False).values('name'))
    if request.is_ajax():
        data = simplejson.dumps(applicants)
        return HttpResponse(data, mimetype="application/json")
    else:
        applicants = list(Candidate.objects.filter(job=job_id, filtered_out=False).values('name'))

        data = simplejson.dumps(applicants)
        return HttpResponse(data, mimetype="application/json")

@login_required
def skill_filter(request, job_id):
    job_skills = Job.objects.get(pk=job_id).skillset
#    if request.method == "POST" and request.is_ajax:
#        filtered_out = 0
#        for candidate in Candidate.objects.filter(job=job_id):
#            applicant_skills = candidate.skillset
#            if set(job_skills).issubset(set(applicant_skills)):
#                pass
#            else:
#                candidate.is_filtered = True
#                candidate.save()
#                filtered_out += 1
#        return HttpResponse(filtered_out, mimetype="application/json")
    if request.method == "POST":
        import sys
        filtered_out = 0
        for candidate in Candidate.objects.filter(job=job_id, filtered_out=False):
            applicant_skills = candidate.skillset
            if set(job_skills).issubset(set(applicant_skills)):
                pass
            else:
                candidate.filtered_out = True
                candidate.save()
                filtered_out += 1
        return HttpResponseRedirect('/job/' + job_id + '/')

@login_required
def academic_filter(request, job_id):
#        filtered_out = 0
    job_academics = Job.objects.get(pk=job_id).academics
#        for candidate in Candidate.objects.filter(job=job_id):
#            applicant_academics = candidate.academics
#            if set(job_academics).issubset(set(applicant_academics)):
#                pass
#            else:
#                candidate.is_filtered = True
#                candidate.save()
#                filtered_out += 1
#        return HttpResponse(filtered_out, mimetype="application/json")
    if request.method == "POST":
        filtered_out = 0
        for candidate in Candidate.objects.filter(job=job_id):
            applicant_academics = candidate.academics
            if set(job_academics).issubset(set(applicant_academics)):
                continue
            else:
                candidate.filtered_out = True
                candidate.save()
                filtered_out += 1
        return HttpResponseRedirect('/job/' + job_id + '/')

def process(text):
    tokens = nltk.word_tokenize(text)
    stopwords = nltk.corpus.stopwords.words('english')
    content = [w for w in text if w.lower() not in stopwords]
    names = nltk.corpus.names
    male_names = names.words('male.txt')
    female_names = names.words('female.txt')
    content2 = [i for i in content if i.lower() not in male_names]
    content3 = [i for i in content2 if i.lower() not in female_names]
    return content3

def compare(text1, text2):
    ratio = jellyfish.jaro_distance(str(set(text1)), str(set(text2)))
    return ratio

@login_required
def best_match(request, job_id):
    ratios = {}
    description = process(Job.objects.get(pk=job_id).description)
#    if request.is_ajax:
#        for candidate in Candidate.objects.filter(job=job_id):
#            text2 = process(candidate.cover_letter)
#            record = compare(description, text2)
#            ratios[candidate.id] = record
#        data = simplejson.dumps(ratios)
#        best = max(ratios.iterkeys(), key=lambda k: ratios[k])
#        return HttpResponse(best, mimetype="application/json")
#    else:
    for candidate in Candidate.objects.filter(job=job_id):
        text2 = process(candidate.cover_letter)
        record = compare(description, text2)
        ratios[candidate.id] = record
    data = simplejson.dumps(ratios)
    best = max(ratios.iterkeys(), key=lambda k: ratios[k])
    output = Candidate.objects.get(id=best)
    return render_to_response("main/best_match.html", locals(), context_instance=RequestContext(request))


def post_job(request):
    if request.method == "POST":
        form = JobForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            saves = Job(owner = request.user, age_limit = data['age_limit'], name = data['title'],
                description = data['description'], skillset = data['skillset'], years_of_experience = data['years_of_experience'],
                academics = data['academics'], applicant_limit = data['applicant_limit'],
                last_application_date = data['last_application_date'])
            saves.save()
            my_jobs = Job.objects.filter(owner=request.user.id)
            return render_to_response("main/admin-panel.html", locals(), context_instance=RequestContext(request))
    else:
        form = JobForm()
    return render_to_response("main/post_job.html", locals(), context_instance=RequestContext(request))


def apply(request, job_id):
    if request.method == "POST":
        form = ApplicationForm(request.POST, request.FILES)
        current_job = Job.objects.get(id=job_id)
        if form.is_valid():
            data = form.cleaned_data
            saves = Candidate(job=current_job, name = data['name'], email = data['email'], years_of_experience = data['years_of_experience'],
                skillset = data['skillset'], academics = data['academics'], number = data['number'], cover_lettr = data['cover_letter'], cv = request.FILES['cv'])
            saves.save()
            return render_to_response("main/application_sent.html", context_instance = RequestContext(request))
    else:
        form = ApplicationForm()
        job = Job.objects.get(id=job_id)
        current_job = Job.objects.get(id=job_id)
    return render_to_response("main/apply.html", locals(), context_instance=RequestContext(request))

def filter(request, job_id, candidate_id):
    if request.method == "POST":
        current = Candidate.objects.get(id=candidate_id, job=job_id)
        current.filtered_out = True
        current.save()
        return HttpResponseRedirect('/job/' + job_id + '/')

def shortlist(request, job_id, candidate_id):
    candidate = Candidate.objects.get(id=candidate_id)
    job = Job.objects.get(id=job_id)
    if request.method == "POST":
        try:
            fetch = Shortlist.objects.get(job=job, can_id=candidate_id) == ''
            return HttpResponseRedirect('/job/' + job_id + '/')
        except Shortlist.DoesNotExist:
            saves = Shortlist(job=job, email=candidate.email, name = candidate.name, can_id = candidate_id)
            saves.save()
            can = Candidate.objects.get(id=candidate_id)
            can.shortlisted = True
            can.save()
            return HttpResponseRedirect('/job/' + job_id + '/')

@login_required
def xperience_filter(request, job_id):
    job_xperience = Job.objects.get(pk=job_id).years_of_experience
    #    if request.method == "POST" and request.is_ajax:
    #        filtered_out = 0
    #        for candidate in Candidate.objects.filter(job=job_id):
    #            applicant_skills = candidate.skillset
    #            if set(job_skills).issubset(set(applicant_skills)):
    #                pass
    #            else:
    #                candidate.is_filtered = True
    #                candidate.save()
    #                filtered_out += 1
    #        return HttpResponse(filtered_out, mimetype="application/json")
    if request.method == "POST":
        import sys
        filtered_out = 0
        for candidate in Candidate.objects.filter(job=job_id, filtered_out=False):
            applicant_xperience = candidate.years_of_experience
            if int(job_xperience) <= int(applicant_xperience):
                pass
            else:
                candidate.filtered_out = True
                candidate.save()
                filtered_out += 1

templates/main/admin-panel.html
{%extends "base.html" %}

{% block content %}
    <div class="row">
    <div class="span4"></div>
    <div class="span4"><a href="/post_job/" class="btn btn-inverse btn-large btn-block">Post A Job</a></div>
    </div>
    <p><h4>YOUR JOBS:</h4></p>
    <br>
    <table class="table table-condensed">
    <tr>
        <td>Name</td>
        <td>Applicants</td>
        <td>Shortlisted</td>
        <td>Active</td>
        <td>Deactivate</td>
    </tr>
    {% for job in my_jobs %}
    <tr>
        <td><a href="/job/{{ job.id }}/">{{ job.name }}</a></td>
        <td>{{ job.applicants }}</td>
        <td>{{ job.applicants }}</td>
        <td>{{ job.is_active }}</td>
        <td><a href="/post_job/" class="btn btn-small btn-warning">Deactivate</a></td>
    </tr>
    {% endfor %}
    </table>

{% endblock %}

templates/main/application_sent.html
<!DOCTYPE html>
<html>
<head>
    <title>APPLICATION SENT</title>
</head>
<body>
APPLiCATION SENT
</body>
</html>

templates/main/apply.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APPLICATION</title>
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <style type="text/css">
        body {
            padding-top: 15px;
            padding-bottom: 40px;
        }

    </style>
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/style.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/datepicker.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/tagmanager.css" rel="stylesheet">
    <style>
        p{
            font: monospace;
            font-size: 16px;
        }
        input{
            font-size: 16px;
        }
        #job{
            float: right;
            text-align: right;
        }
    </style>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">APPLICATION PAGE</a>
        </div>
    </div>
</div>
<div class="container">
<br>
<br>
<div class="row">
    <div class="span1"></div>
    <div class="span5">
        <form method="POST" action=".">
            {% csrf_token %}
            {%for field in form %}
                {%if field.errors %}
                    <div class="control-group error">

                        <p>{{ field.label }}</p>
                        {{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                {% else %}
                    <div class="control-group">
                        <p>{{ field.label }}</p>
                        {{ field }}
                    </div>
                {% endif %}

            {% endfor %}
            <br>
            <div class="small-2 small-offset-1 columns">
                <button class="btn btn-inverse btn-large" type="submit">Apply</button>
            </div>
        </form>
    </div>
    <div class="span5" id="job"><h3>{{ job.name }}</h3>
    <p>{{ job.description }}</p>
    <p><h5>Skills required:</h5> {{ job.skillset }}</p>
    <p><h5>Academics required:</h5> {{ job.academics }}</p>
    {% if job.age_limit %}<p><h5>Age limit:</h5> {{ job.age_limit }}</p>{% endif %}
    </div>
</div>

</div>
<footer class="footer">[Footer here]</footer>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/tagmanager.js"></script>
<script>
    $('.datepicker').datepicker()
</script>

<script>
    jQuery("#id_skillset").tagsManager();
</script>
<script>
    jQuery("#id_academics").tagsManager();
</script>

</body>
</html>

templates/main/best_match.html
{% extends "base.html" %}

{% block content %}
    <h3>BEST MATCH</h3>
    <br>
    <p>{{ output.name }}</p>

{% endblock %}

templates/main/details.html
{% extends "base.html" %}
{% block content %}
    <h3>Job: {{ details.name }}</h3>
    <h4>Application URL: <a href="{{ details.job_url }}">{{ details.job_url }}</a></h4>
    <h5><a href="/{{ job_id }}/shortlisted/">View shortlisted candidates</a></h5>
    <hr>
    <br>
    <div class="row">
        <div class="span2"></div>
        <div class="span2"><form method="POST" action="/skill_filter/{{ job_id }}/">
            {% csrf_token %}
            <button class="btn btn-inverse btn-large" type="submit">skill based filter</button>
        </form></div>
        <div class="span2"><form method="POST" action="/academic_filter/{{ job_id }}/">
            {% csrf_token %}
            <button class="btn btn-inverse btn-large" type="submit">academic filter</button>
        </form></div>
        <div class="span2"><form method="POST" action="/experience_filter/{{ job_id }}/">
            {% csrf_token %}
            <button class="btn btn-inverse btn-large" type="submit">experience filter</button>
        </form></div>
        <div class="span2"><div class="span2"><a href="/best_match/{{ job_id }}/"><button class="btn btn-large">Best match</button></a></div></div>
        <div class="span2"></div>
    </div>


    <h5>APPLICANTS:</h5>
    <table class="table table-condensed">
        <tr>
            <td>Name</td>
            <td>Shortlist</td>
            <td>Filter out</td>
            <td>Skills</td>
            <td>Academics</td>
            <td>Curriculum Vitae</td>
            <td>Cover letter</td>
        </tr>
        {% for candidate in candidates %}
        <tr>
            <td>{{ candidate.name }}</td>
            <td><form method="POST" action="/{{ job_id }}/{{ candidate.id }}/shortlist/">
                {% csrf_token %}
                <input type="submit" name="shortlist" value="shortlist" />
            </form></td>
            <td><form method="POST" action="/{{ job_id }}/{{ candidate.id }}/filter/">
                {% csrf_token %}
                <input type="submit" name="filter" value="filter" />
            </form></td>
            <td>View Skills
            <div style="display: none">{{ candidate.skillset }}</div>
            </td>
            <td>View Academics
                <div style="display: none">{{ candidate.academics }}</div>
            </td>
            <td>View CV
                <div style="display: none">{{ candidate.academics }}</div>
            </td>
            <td>View Cover letter
                <div style="display: none">{{ candidate.academics }}</div>
            </td>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/main/post_job.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="span2"></div>
        <div class="span5">
            <form method="POST" action=".">
                {% csrf_token %}
                {%for field in form %}
                    {%if field.errors %}
                        <div class="control-group error">

                        <p>{{ field.label }}</p>
                        {{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                        </div>
                    {% else %}
                    <div class="control-group">
                    <p>{{ field.label }}</p>
                    {{ field }}
                    </div>
                    {% endif %}

                {% endfor %}
                <br>
                <div class="small-2 small-offset-1 columns">
                    <button class="btn btn-inverse btn-large" type="submit">Post job</button>
                </div>
            </form>
        </div>
        <div class="span2"></div>
    </div>
{% endblock %}

templates/main/shortlisted.html
{% extends "base.html" %}
{% block content %}

    <table class="table table-condensed">
        <tr>
            <td>Name</td>
            <td>Details</td>
            <td>Remove</td>
        </tr>
        {% for shortlist in shortlisted %}
            <tr>
                <td>{{ shortlist.name }}</td>
                <td><a href="#">View Details</a></td>
                <td><form method="POST" action="/{{ job_id }}/{{ candidate.id }}/filter/">
                    {% csrf_token %}
                    <input type="submit" name="filter" value="Remove" />
                </form></td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}